# Server Configuration
server.port=8080

# WMATA API Configuration
wmata.api.key=2b82adaba418491e8729b685469478f7

# Database Configuration (H2)
spring.datasource.url=jdbc:h2:file:~/wmata.db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jackson.mapper.accept-case-insensitive-properties=true

# Logging
logging.level.com.wmata=DEBUG